// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: trading.proto

package server

import (
	"context"

	"ws_trading/rpc/internal/logic"
	"ws_trading/rpc/internal/svc"
	"ws_trading/rpc/trading"
)

type TradingServiceServer struct {
	svcCtx *svc.ServiceContext
	trading.UnimplementedTradingServiceServer
}

func NewTradingServiceServer(svcCtx *svc.ServiceContext) *TradingServiceServer {
	return &TradingServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TradingServiceServer) SetTradingSignal(ctx context.Context, in *trading.SetTradingSignalRequest) (*trading.SetTradingSignalResponse, error) {
	l := logic.NewSetTradingSignalLogic(ctx, s.svcCtx)
	return l.SetTradingSignal(in)
}

func (s *TradingServiceServer) GetTrading(ctx context.Context, in *trading.GetTradingRequest) (*trading.GetTradingResponse, error) {
	l := logic.NewGetTradingLogic(ctx, s.svcCtx)
	return l.GetTrading(in)
}
