// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type Base struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type BaseListResponse struct {
	Base
	Data  interface{} `json:"data"`
	Total int         `json:"total"`
}

type BasePageResponse struct {
	Base
	Data     interface{} `json:"data"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
}

type BaseResponse struct {
	Base
	Data interface{} `json:"data"`
}

type GetTradingRequest struct {
	Id int `json:"id"`
}

type SetTradingSignalRequest struct {
	Signal string `json:"signal"`
}
