// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"
	"time"

	"ws_trading/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/trading/:id",
				Handler: GetTradingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trading/signal",
				Handler: SetTradingSignalHandler(serverCtx),
			},
		},
		// rest.WithPrefix("/trading"),··
		rest.WithTimeout(10000*time.Millisecond),
	)
}
